// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://snommmnxkkhtfwixfpso.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNub21tbW54a2todGZ3aXhmcHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2MjczMjgsImV4cCI6MjA0ODIwMzMyOH0.qFRgurz-nFsk62ZFGH4pFSITmDTQeJCaFmkv7ToXTPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);